services:
  tfserving:
    image: tensorflow/serving:latest
    container_name: tfserving
    # Монтируем каталог с моделью
    volumes:
      - ./models/saved_model:/models/saved_model:ro
    # REST на 8501, gRPC на 8500
    expose:
      - "8503"
      - "8502"
    command: >
      --rest_api_port=8503
      --grpc_port=8502
      --model_name=saved_model
      --model_base_path=/models/saved_model
    networks:
      - appnet

  streamlit:
    build:
      context: ./streamlit_app
    container_name: streamlit_app
    volumes:
      - ./streamlit_app/secrets.toml:/app/secrets.toml:ro
    ports:
      - "8501:8501"
    environment:
      # URL для доступа к TF-Serving из Streamlit
      - TF_SERVER_URL=http://tfserving:8503/v1/models/saved_model:predict
    depends_on:
      - tfserving
    networks:
      - appnet

networks:
  appnet:
    driver: bridge