services:
  streamlit:
    build: ./streamlit_app
    volumes:
      - ./streamlit_app/secrets.toml:/app/secrets.toml:ro
    ports:
      - "8501:8501"
    environment:
      - TF_SERVER_URL=http://tfserving:8501/v1/models/saved_model:predict
    networks:
      - appnet

  tfserving:
    image: tensorflow/serving:latest
    # Монтируем каталог с моделью
    volumes:
      - ./models/saved_model:/models/saved_model:ro
    # Параметры запуска: имя модели и путь
    command: >
      --model_name=saved_model
      --model_base_path=/models/saved_model
    # Сеть для внутреннего обращения
    networks:
      - appnet

networks:
  appnet:
    driver: bridge